const Resources = {
  common: {
    bgHome: require('../assets/images/banner-top.png'),
    iconSearch: require('../assets/images/ico-search-green.png'),
    iconSearch2: require('../assets/images/ico-search-gray.png'),
    imgTop: require('../assets/images/img-top.png'),
    iconClock: require('../assets/images/ico-gio.png'),
    bannerHome1: require('../assets/images/banner_home01.png'),
    bannerHome2: require('../assets/images/banner_home02.png'),
    imgRandom: require('../assets/images/img1.png'),
    iconArrowRight: require('../assets/images/arrow-gray.png'),
    iconArrowRight2: require('../assets/images/arrow-white.png'),
    iconMenu: require('../assets/images/btn-mennu.png'),
    iconTracu1: require('../assets/images/tab-tracuu.png'),
    iconTracu2: require('../assets/images/tab-tracuu-o.png'),
    iconDanhDau1: require('../assets/images/tab-dd.png'),
    iconDanhDau2: require('../assets/images/tab-dd-o.png'),
    iconTinTuc1: require('../assets/images/tab-dx.png'),
    iconTinTuc2: require('../assets/images/tab-dx-o.png'),
    iconCaNhan1: require('../assets/images/ico-user.png'),
    iconCaNhan2: require('../assets/images/ico-user-white.png'),
    iconThongBao1: require('../assets/images/tab-tb.png'),
    iconThongBao2: require('../assets/images/tab-tb-o.png'),
    bgDrawer: require('../assets/images/bg-dn.png'),
    avatar1: require('../assets/images/avatar-white.png'),
    avatar2: require('../assets/images/avatar-blue.png'),
    iconLan: require('../assets/images/ico_ngonngu.png'),
    iconMarked: require('../assets/images/ico-dd.png'),
    iconSignin: require('../assets/images/ico-dnhap.png'),
    iconHistory: require('../assets/images/ico-dx.png'),
    iconInfo: require('../assets/images/ico-tt.png'),
    bgCommon: require('../assets/images/bg-dk.png'),
    bgUser: require('../assets/images/bg-dn.png'),
    iconArrowLeft: require('../assets/images/arrow-white2.png'),
    iconEdit: require('../assets/images/ico-edit-w.png'),
    imgQR: require('../assets/images/1.png'),
    iconSettings: require('../assets/images/pb.png'),
    iconSupport: require('../assets/images/ht.png'),
    iconSecurity: require('../assets/images/lk.png'),
    iconClose: require('../assets/images/ico-close.png'),
  },
};
export default Resources;
